name: Build and Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Validate markdown files
        run: npm run validate
        
      - name: Check tmux configs
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux
          for config in configs/*.conf; do
            echo "Validating $config"
            tmux -f "$config" new-session -d "echo 'Config test'" || exit 1
            tmux kill-server
          done